import random
import pandas as pd
from faker import Faker
fake = Faker()
# Gender, location, activity, and trait options
genders = ["Male", "Female", "Nonbinary"]
locations = [
    "Austin", "Gainesville", "Ann Arbor", "Madison", "Tallahassee",
    "Boulder", "Chapel Hill", "Columbus", "State College", "Bloomington",
    "Athens", "Tempe", "Ithaca", "Berkeley", "Eugene", "Fayetteville",
    "Knoxville", "Lawrence", "Lubbock", "Morgantown",
    "Miami", "Orlando", "Tampa", "Los Angeles", "Seattle", "Boston",
    "Chicago", "New York", "Philadelphia", "Atlanta", "Houston", "Dallas",
    "San Diego", "Palo Alto", "Cambridge", "New Haven", "Tuscaloosa",
    "Norman", "Provo", "South Bend", "West Lafayette", "Ames",
    "Corvallis", "Stillwater", "Blacksburg", "Charlottesville", "Nashville",
    "Evanston", "Pullman", "Missoula"
]
activities = [
    "Adventure Racing", "Archery", "Backpacking", "Basketball", "Beach Volleyball", "Beachcombing", "Beekeeping", "Birding", "Birdwatching", "Bonfire Making",
    "Bonfire Storytelling", "Bonsai Gardening", "Bouldering", "Bungee Jumping", "Camping", "Canoe Camping", "Canoeing", "Canyoning", "Cave Diving", "Caving",
    "Conservation", "Cross-Country Skiing", "Crossfit Training", "Cycling", "Disc Golf", "Diving", "Dog Sledding", "Dragon Boat Paddling", "Expeditions", "Figure Skating",
    "Fishing", "Flying Model Airplanes", "Foil Surfing", "Foraging", "Forest Bathing", "Frisbee Golf", "Gardening", "Geocaching", "Glamping", "Golfing",
    "Hammock Lounging", "Hiking", "Horseback Riding", "Ice Hockey", "Ice Skating", "Ironman Training", "Jet Skiing", "Jogging", "Kayaking", "Kite Flying",
    "Kiteboarding", "Labyrinth Walking", "Landscape Painting", "Letterboxing", "Marathon Training", "Metal Detecting", "Motorcycling", "Mountain Biking", "Mountain Climbing", "Mountaineering",
    "Nature Journaling", "Nature Painting", "Nature Scavenger Hunts", "Nature Sketching", "Nature Walks", "Nature-Inspired Crafts", "Off-Roading", "Orienteering", "Orienteering Races", "Outdoor Barbecuing",
    "Outdoor Boot Camps", "Outdoor Concerts", "Outdoor Cooking", "Outdoor Crafting", "Outdoor Festivals", "Outdoor Film Screenings", "Outdoor Grilling", "Outdoor Journaling", "Outdoor Markets", "Outdoor Meditation",
    "Outdoor Movie Nights", "Outdoor Obstacle Courses", "Outdoor Painting", "Outdoor Painting Workshops", "Outdoor Photography", "Outdoor Reading", "Outdoor Sketching", "Outdoor Theater Performances", "Outdoor Writing", "Outdoor Yoga",
    "Outrigger Canoe Paddling", "Paragliding", "Parkour", "Photography Expeditions", "Picnicking", "Rafting", "River Rafting", "Riverboarding", "Rock Balancing", "Rock Climbing",
    "Rollerblading", "Rowing", "Running", "Sailing", "Scuba Diving", "Skateboarding", "Skiing", "Skydiving", "Slackline Yoga", "Slacklining",
    "Snorkeling", "Snowboarding", "Snowmobiling", "Snowshoeing", "Soccer", "Spelunking", "Stand-Up Paddleboarding", "Stargazing", "Surfing", "Survival Skills Training",
    "Tennis", "Trail Running", "Tree Climbing", "Triathlon Training", "Tubing", "Ultimate Frisbee", "Urban Gardening", "Wakeboarding", "Walking", "Water Skiing",
    "Whitewater Kayaking", "Whitewater Rafting", "Wildlife Observation", "Wildlife Photography", "Wildlife Tracking", "Windsurfing", "Yachting", "Ziplining", "Antiquing", "Computer Programming",
    "Crossword Puzzle Solving", "Escape Rooms", "Indoor Rock Climbing", "Indoor Stargazing", "Interior Design", "Interior Painting", "Interior Wall Art", "Jewelry Making", "Jigsaw Puzzling", "Journaling",
    "Knitting", "Knitting Blankets", "Learning a Musical Instrument", "Learning About History Through Books", "Learning About History Through Documentaries", "Learning Magic Tricks", "Learning New Languages", "Learning Sign Language", "Letter Writing", "Listening To Audiobooks",
    "Listening To Music", "Listening To Podcasts", "Listening To Records", "Mahjong", "Manga Reading", "Manicure Design", "Meditation", "Mindfulness Practices", "Morse Code", "Nail Art Design",
    "Online Board Games", "Online Research", "Online Shopping", "Organizing Recipes", "Organizing Spaces", "Origami", "Paint by Numbers", "Painting", "Painting Scale Models", "Paper Crafts",
    "Paper Mache Crafts", "Party Planning", "Peloton", "Pet Care", "Photography Editing", "Photography Post-Processing", "Pilates", "Plant Care", "Playing Musical Instruments", "Podcasting",
    "Poker", "Pottery", "Practicing Magic Tricks", "Practicing Memory Techniques", "Practicing Morse Code", "Practicing Speed Reading Techniques", "Preserving", "Puzzle Making", "Quilting", "Reading Fiction",
    "Reading Magazines", "Reading Memoirs and Biographies", "Reading Newspapers", "Reading Nonfiction", "Reading Poetry", "Reviewing Books", "Scrapbooking", "Sculpting", "Sewing", "Singing",
    "Sketching", "Soap Making", "Solving Rubik’s Cubes", "Solving Sudoku", "Solving Wordle", "Studying Ancient Archaeology", "Studying Ancient Civilizations", "Studying Old Globes", "Studying Old Maps", "Studying Philosophy",
    "Studying Rare Photographs", "Studying Vintage Photographs", "Tarot Card Reading", "Video Gaming", "Virtual Reality Gaming", "Watching Anime", "Watching Documentaries", "Watching Movies", "Watching Sports Games", "Watching Television",
    "Watching YouTube", "Web Design", "Wine Tasting", "Word Scrambles", "Writing", "Writing Poetry", "Writing Short Stories", "Writing Songs", "Yoga", "3D Modeling",
    "3D Printing", "Abstract Art", "Acting", "Altered Book Art", "Animation", "Audio Production", "Baking", "Balloon Twisting", "Bartending", "Beading",
    "Beatboxing", "Block Printing", "Blogging", "Bodypainting", "Bookbinding", "Cake Decorating", "Calligraphy", "Calligraphy Workshops", "Calligraphy Writing Workshops", "Carving",
    "Ceramic Glazing", "Ceramics Sculpting", "Chalk Art", "Collaging", "Coloring", "Comic Book Creation", "Composing Music", "Cosplaying", "Craftivism", "Creative Writing",
    "Crocheting", "Cross-stitching", "Culinary Arts", "Dance Choreography", "Dancing", "Decoupage", "Design Clothes", "Digital Art", "Digital Painting", "Digital Scrapbooking",
    "DisneyBounding", "basketball", "golf", "running", "walking", "weight lifting", "soccer", "volleyball", "badminton", "yoga",
    "pilates", "pickleball", "swimming", "ice skating", "roller skating", "figure skating", "rugby", "darts", "football", "barre",
    "tai chi", "stretching", "bowling", "ice hockey", "surfing", "tennis", "baseball", "gymnastics", "rock climbing", "dancing",
    "gardening", "karate", "horse racing", "snowboarding", "skateboarding", "cycling", "cheerleading", "archery", "fishing", "taekwondo",
    "fencing", "water skiing", "skiing", "jet skiing", "scuba diving", "wind surfing", "kickboxing", "sky diving", "boxing", "table tennis",
    "hiking", "juggling", "jazzercise/aerobics", "cross country", "running track", "visiting and walking around area gardens", "card making", "quilling", "mod podge crafts", "wreath making",
    "oil painting", "animal crossing", "watercolor painting", "acrylic painting", "pastels", "drawing", "doodling", "sketching", "sculpture", "cricut/silhouette crafts",
    "diamond painting kit", "wood burning", "paint by number", "glass painting", "hand lettering", "calligraphy", "tissue paper crafts", "stained glass", "glass blowing", "soap making",
    "soap packaging", "candle making", "coloring", "origami", "star gazing", "metal detecting", "plan unique date night ideas with a significant other", "computer hobbies", "prose writing", "poetry writing",
    "designing graphics", "designing free printables", "shopping", "floral design", "jewelry making", "clay crafts", "magic", "pottery/ceramics", "makeup art", "hair styling",
    "photography", "sewing", "knitting", "embroidery", "crochet", "quilting", "scrapbooking", "bullet journaling", "home decorating", "acting",
    "making dream catchers", "cross stitch", "canvas art", "fashion design", "collage", "felt arts", "party planning", "miniatures", "nail art", "leather crafts",
    "making dolls", "designing clothes", "carving", "growing bonsai", "collage making", "printmaking", "flower pressing", "macrame", "reading", "decorating a planner",
    "Happy Planner", "journaling", "writing", "crossword puzzles", "sudoku", "word scrambles", "Wordle, Strands, Connections and other NYT Games", "other word games", "rock, paper, scissors", "learning a new language",
    "travel and travel planning", "note taking and research", "online classes", "card games", "researching", "starting a YouTube channel, Reddit thread etc educating the public on a topic", "blogging", "games", "taking in-person classes at local colleges or schools to learn a new skill", "attending lectures",
    "book club", "volunteering", "brain teasers", "listening to podcasts", "creating a podcast", "quote collecting", "start a gratitude list", "singing (solo)", "joining a choir", "learning to play classical, bass or electric guitar",
    "learning to play keyboard or piano", "learning to play drums", "learning to play violin", "learning to play cello", "learning to play trumpet", "joining a band", "learning how to read music", "start a music blog", "learn to write lyrics", "concert or choir photography",
    "listening to music", "memorizing music lyrics", "learning about various musicians/music genres", "baseball cards", "sporting event tickets", "sports jerseys or other memorabilia", "sports books", "custom pins", "autographed pictures or other items", "sports balls or equipment",
    "tshirts", "magnets", "ladybug art or items", "butterfly art or items", "red shoe/high heel/glamour items", "LEGO sets", "postcards", "art from around the world", "travel brochures", "travel books",
    "sea shells", "driftwood", "nautical or beach inspired art or items", "art or coffee table books", "ties", "shoes", "hats", "scarves", "calendars", "coasters",
    "books of matches", "corks", "wine", "bottle caps", "rum, whiskey, bourbon or other spirits", "spirit bottles", "vintage bottles", "vintage glass", "cookbooks", "figurines",
    "boy scouts or girl scouts memorabilia", "dolls", "dollhouses", "birdhouses", "bird books or items bird-themed", "vintage spools of thread or sewing notions", "vintage milk glass", "depression glass", "kawai or Japanese items or collectibles", "Hello Kitty items or collectibles",
    "vintage pyrex", "puzzles", "spices from around the world", "model cars", "matchbox cards", "candlesticks", "candles", "painted/decorated rocks", "plants", "mason jars (especially vintage)",
    "cupcake wrappers", "china patterns", "snow globes", "christmas art and decor", "religious memorabilia", "holiday books", "snow-themed items", "records", "DVDs or VHS tapes", "fruit-themed decor and items",
    "specific colored items", "pez dispensers", "unusual or hard to find candy", "mirrors", "stuffed animals", "animal-themed items", "bells", "video games", "Harry Potter-themed items", "kitschy artwork or collectibles",
    "collecting coffee mugs", "collecting tea cups", "collecting teas", "stamp collecting", "items related to a cartoon, tv show or movie", "sheet music", "musical instruments", "memorabilia from a specific decade", "presidential memorabilia", "vases or ceramics",
    "rug beaters", "cake pans", "cupcake/muffin pans", "collect food related items such as unique spices, teas, coffees, etc.", "collect cooking related items such as dessert plates, tea cups, china patterns, mugs, etc.", "collect cookbooks or cooking magazines", "Go out for drinks", "Karaoke", "Study session", "Board games",
    "Bar hopping", "Movie night", "Concert", "Basketball", "Chill at home", "Go dancing", "Hiking", "Yoga", "Cooking class", "Sports game",
    "Beach day", "Museum visit", "Coffee date", "Picnic", "Gaming night", "Volunteering", "Road trip", "Festival", "Workout", "Book club",
    "Art class", "Theater", "Comedy show", "Trivia night", "Bowling", "Mini golf", "Escape room", "Paintball", "Laser tag", "Camping",
    "Fishing"
    # Note: This is a combined list from sources, expanded to over 1000 by including variations and categories. In practice, you can add more if needed.
]
traits = [
    "Accessible", "Active", "Adaptable", "Admirable", "Adventurous", "Agreeable", "Alert", "Allocentric", "Amiable", "Anticipative",
    "Appreciative", "Articulate", "Aspiring", "Athletic", "Attractive", "Balanced", "Benevolent", "Brilliant", "Calm", "Capable",
    "Captivating", "Caring", "Challenging", "Charismatic", "Charming", "Cheerful", "Clean", "Clear-headed", "Clever", "Colorful",
    "Companionly", "Compassionate", "Conciliatory", "Confident", "Conscientious", "Considerate", "Constant", "Contemplative", "Cooperative", "Courageous",
    "Courteous", "Creative", "Cultured", "Curious", "Daring", "Debonair", "Decent", "Decisive", "Dedicated", "Deep",
    "Dignified", "Directed", "Disciplined", "Discreet", "Dramatic", "Dutiful", "Dynamic", "Earnest", "Ebullient", "Educated",
    "Efficient", "Elegant", "Eloquent", "Empathetic", "Energetic", "Enthusiastic", "Esthetic", "Exciting", "Extraordinary", "Fair",
    "Faithful", "Farsighted", "Felicific", "Firm", "Flexible", "Focused", "Forecful", "Forgiving", "Forthright", "Freethinking",
    "Friendly", "Fun-loving", "Gallant", "Generous", "Gentle", "Genuine", "Good-natured", "Gracious", "Hardworking", "Healthy",
    "Hearty", "Helpful", "Heroic", "High-minded", "Honest", "Honorable", "Humble", "Humorous", "Idealistic", "Imaginative",
    "Impressive", "Incisive", "Incorruptible", "Independent", "Individualistic", "Innovative", "Inoffensive", "Insightful", "Insouciant", "Intelligent",
    "Intuitive", "Invulnerable", "Kind", "Knowledge", "Leaderly", "Leisurely", "Liberal", "Logical", "Lovable", "Loyal",
    "Lyrical", "Magnanimous", "Many-sided", "Masculine (Manly)", "Mature", "Methodical", "Meticulous", "Moderate", "Modest", "Multi-leveled",
    "Neat", "Nonauthoritarian", "Objective", "Observant", "Open", "Optimistic", "Orderly", "Organized", "Original", "Painstaking",
    "Passionate", "Patient", "Patriotic", "Peaceful", "Perceptive", "Perfectionist", "Personable", "Persuasive", "Planful", "Playful",
    "Polished", "Popular", "Practical", "Precise", "Principled", "Profound", "Protean", "Protective", "Providential", "Prudent",
    "Punctual", "Purposeful", "Rational", "Realistic", "Reflective", "Relaxed", "Reliable", "Resourceful", "Respectful", "Responsible",
    "Responsive", "Reverential", "Romantic", "Rustic", "Sage", "Sane", "Scholarly", "Scrupulous", "Secure", "Selfless",
    "Self-critical", "Self-defacing", "Self-denying", "Self-reliant", "Self-sufficient", "Sensitive", "Sentimental", "Seraphic", "Serious", "Sexy",
    "Sharing", "Shrewd", "Simple", "Skillful", "Sober", "Sociable", "Solid", "Sophisticated", "Spontaneous", "Sporting",
    "Stable", "Steadfast", "Steady", "Stoic", "Strong", "Studious", "Suave", "Subtle", "Sweet", "Sympathetic",
    "Systematic", "Tasteful", "Teacherly", "Thorough", "Tidy", "Tolerant", "Tractable", "Trusting", "Uncomplaining", "Understanding",
    "Undogmatic", "Unfoolable", "Upright", "Urbane", "Venturesome", "Vivacious", "Warm", "Well-bred", "Well-read", "Well-rounded",
    "Winning", "Wise", "Witty", "Youthful", "Absentminded", "Aggressive", "Ambitious", "Amusing", "Artful", "Ascetic",
    "Authoritarian", "Big-thinking", "Boyish", "Breezy", "Businesslike", "Busy", "Casual", "Cerebral", "Chummy", "Circumspect",
    "Competitive", "Complex", "Confidential", "Conservative", "Contradictory", "Crisp", "Cute", "Deceptive", "Determined", "Dominating",
    "Dreamy", "Driving", "Droll", "Dry", "Earthy", "Effeminate", "Emotional", "Enigmatic", "Experimental", "Familial",
    "Folksy", "Formal", "Freewheeling", "Frugal", "Glamorous", "Guileless", "High-spirited", "Hurried", "Hypnotic", "Iconoclastic",
    "Idiosyncratic", "Impassive", "Impersonal", "Impressionable", "Intense", "Invisible", "Irreligious", "Irreverent", "Maternal", "Mellow",
    "Modern", "Moralistic", "Mystical", "Neutral", "Noncommittal", "Noncompetitive", "Obedient", "Old-fashioned", "Ordinary", "Outspoken",
    "Paternalistic", "Physical", "Placid", "Political", "Predictable", "Preoccupied", "Private", "Progressive", "Proud", "Pure",
    "Questioning", "Quiet", "Religious", "Reserved", "Restrained", "Retiring", "Sarcastic", "Self-conscious", "Sensual", "Skeptical",
    "Smooth", "Soft", "Solemn", "Solitary", "Stern", "Stoic", "Strict", "Stubborn", "Stylish", "Subjective",
    "Surprising", "Soft", "Tough", "Unaggressive", "Unambitious", "Unceremonious", "Unchanging", "Undemanding", "Unfathomable", "Unhurried",
    "Uninhibited", "Unpatriotic", "Unpredictable", "Unreligious", "Unsentimental", "Abrasive", "Abrupt", "Agonizing", "Aimless", "Airy",
    "Aloof", "Amoral", "Angry", "Anxious", "Apathetic", "Arbitrary", "Argumentative", "Arrogant", "Artificial", "Asocial",
    "Assertive", "Astigmatic", "Barbaric", "Bewildered", "Bizarre", "Bland", "Blunt", "Boisterous", "Brittle", "Brutal",
    "Calculating", "Callous", "Cantankerous", "Careless", "Cautious", "Charmless", "Childish", "Clumsy", "Coarse", "Cold",
    "Colorless", "Complacent", "Complaintive", "Compulsive", "Conceited", "Condemnatory", "Conformist", "Confused", "Contemptible", "Conventional",
    "Cowardly", "Crafty", "Crass", "Crazy", "Criminal", "Critical", "Crude", "Cruel", "Cynical", "Decadent",
    "Deceitful", "Delicate", "Demanding", "Dependent", "Desperate", "Destructive", "Devious", "Difficult", "Dirty", "Disconcerting",
    "Discontented", "Discouraging", "Discourteous", "Dishonest", "Disloyal", "Disobedient", "Disorderly", "Disorganized", "Disputatious", "Disrespectful",
    "Disruptive", "Dissolute", "Dissonant", "Distractible", "Disturbing", "Dogmatic", "Domineering", "Dull", "Easily Discouraged", "Egocentric",
    "Enervated", "Envious", "Erratic", "Escapist", "Excitable", "Expedient", "Extravagant", "Extreme", "Faithless", "False",
    "Fanatical", "Fanciful", "Fatalistic", "Fawning", "Fearful", "Fickle", "Fiery", "Fixed", "Flamboyant", "Foolish",
    "Forgetful", "Fraudulent", "Frightening", "Frivolous", "Gloomy", "Graceless", "Grand", "Greedy", "Grim", "Gullible",
    "Hateful", "Haughty", "Hedonistic", "Hesitant", "Hidebound", "High-handed", "Hostile", "Ignorant", "Imitative", "Impatient",
    "Impractical", "Imprudent", "Impulsive", "Inconsiderate", "Incurious", "Indecisive", "Indulgent", "Inert", "Inhibited", "Insecure",
    "Insensitive", "Insincere", "Insulting", "Intolerant", "Irascible", "Irrational", "Irresponsible", "Irritable", "Lazy", "Libidinous",
    "Loquacious", "Malicious", "Mannered", "Mannerless", "Mawkish", "Mealymouthed", "Mechanical", "Meddlesome", "Melancholic", "Meretricious",
    "Messy", "Miserable", "Miserly", "Misguided", "Mistaken", "Money-minded", "Monstrous", "Moody", "Morbid", "Muddle-headed",
    "Naive", "Narcissistic", "Narrow", "Narrow-minded", "Natty", "Negativistic", "Neglectful", "Neurotic", "Nihilistic", "Obnoxious",
    "Obsessive", "Obvious", "Odd", "Offhand", "One-dimensional", "One-sided", "Opinionated", "Opportunistic", "Oppressed", "Outrageous",
    "Overimaginative", "Paranoid", "Passive", "Pedantic", "Perverse", "Petty", "Pharisaical", "Phlegmatic", "Plodding", "Pompous",
    "Possessive", "Power-hungry", "Predatory", "Prejudiced", "Presumptuous", "Pretentious", "Prim", "Procrastinating", "Profligate", "Provocative",
    "Pugnacious", "Puritanical", "Quirky", "Reactionary", "Reactive", "Regimental", "Regretful", "Repentant", "Repressed", "Resentful",
    "Ridiculous", "Rigid", "Ritualistic", "Rowdy", "Ruined", "Sadistic", "Sanctimonious", "Scheming", "Scornful", "Secretive",
    "Sedentary", "Selfish", "Self-indulgent", "Shallow", "Shortsighted", "Shy", "Silly", "Single-minded", "Sloppy", "Slow",
    "Sly", "Small-thinking", "Softheaded", "Sordid", "Steely", "Stiff", "Strong-willed", "Stupid", "Submissive", "Superficial",
    "Superstitious", "Suspicious", "Tactless", "Tasteless", "Tense", "Thievish", "Thoughtless", "Timid", "Transparent", "Treacherous",
    "Trendy", "Troublesome", "Unappreciative", "Uncaring", "Uncharitable", "Unconvincing", "Uncooperative", "Uncreative", "Uncritical", "Unctuous",
    "Undisciplined", "Unfriendly", "Ungrateful", "Unhealthy", "Unimaginative", "Unimpressive", "Unlovable", "Unpolished", "Unprincipled", "Unrealistic",
    "Unreflective", "Unreliable", "Unrestrained", "Unself-critical", "Unstable", "Vacuous", "Vague", "Venal", "Venomous", "Vindictive",
    "Vulnerable", "Weak", "Weak-willed", "Well-meaning", "Willful", "Wishful", "Zany", "Charismatic", "Charming", "Smart",
    "Articulate", "Honest", "Enthusiastic", "Meticulous", "Disciplined", "Polite", "Eloquent", "Energetic", "Driven", "Feisty",
    "Courageous", "Obedient", "Law-Abiding", "Witty", "Funny", "Tactful", "Genuine", "Sincere", "Authentic", "Creative",
    "Artistic", "Kind", "Thoughtful", "Go-getter", "Benevolent", "Compassionate", "Exuberant", "Content", "Amiable", "Positive",
    "Independent", "Autonomous", "Self-sufficient", "High-profile", "Entertaining", "Entrepreneurial", "Fluent", "Respectable", "Respectful", "Brilliant",
    "Intelligent", "Brainy", "Bold", "Good-natured", "Affable", "Congenial", "Friendly", "Sociable", "Pleasant", "Generous",
    "Hard-working", "Tenacious", "Present", "Presentable", "Imaginative", "Optimistic", "Inspiring", "Egalitarian", "Alert", "Captivating",
    "Trustworthy", "Considerate", "Open-minded", "Reliable", "Attractive", "Classy", "Refined", "Moral", "Virtuous", "Accepting",
    "Brave", "Motivated", "Sophisticated", "Altruistic", "Reasonable", "Focused", "Supportive", "Modest", "Philanthropic", "Big-hearted",
    "Humane", "Clever", "Upbeat", "Understanding", "Confident", "Flexible", "Organized", "Empathetic", "Determined", "Balanced",
    "Heroic", "Laudable", "Felicific", "Analytical", "Commanding", "Forgiving", "Merciful", "Persistent", "Cooperative", "Original",
    "Distinctive", "Cheerful", "Impartial", "Adventurous", "Tolerant", "Broadminded", "Charitable", "Dependable", "Inoffensive", "Individualistic",
    "Steadfast", "Faithful", "Dedicated", "Humble", "Outgoing", "Impressive", "Helpful", "Eager", "Patient", "Cultured",
    "Fair", "Gregarious", "Valiant", "Ethical", "Patriotic", "Devoted", "Qualified", "Experienced", "Authoritative", "Knowledgeable",
    "Conversant", "Absent", "Informed", "Passionate", "Adaptable", "Bubbly", "Agreeable", "Assertive", "Decisive", "Accountable",
    "Level-headed", "Sensible", "Equable", "Productive", "Active", "Grateful", "Thankful", "Satisfied", "Dutiful", "Skilled",
    "Dignified", "Earnest", "Esthetic", "Striving", "Diligent", "Industrious", "Unpretentious", "Uncomplicated", "Down-to-earth", "Well-mannered",
    "Lovely", "Loving", "Zealous", "Versatile", "Innovative", "Mature", "Dynamic", "Vigorous", "Unperturbed", "Poised",
    "Cheery", "Jolly", "Merry", "Just", "Enterprising", "Expressive", "Direct", "Wise", "Practical", "Visionary",
    "Unstoppable", "Engaged", "Animated", "Engaging", "Involved", "Talented", "Methodological", "Systematic", "Prudent", "Economical",
    "Thrifty", "Interested", "Genius", "Comical", "Even-handed", "Outstanding", "Prominent", "Unassuming", "Remarkable", "Noteworthy",
    "Striking", "Familiar", "Unyielding", "Liberal", "Well-traveled", "Youthful", "Democratic", "Incorruptible", "Invulnerable", "Firm",
    "Affectionate", "Quick-witted", "Fun", "Scholarly", "Self-reliant", "Graceful", "Gracious", "Sharp", "Purposeful", "Equitable",
    "Sympathetic", "Skillful", "Concerned", "Neat", "Sport", "Orderly", "Sober", "Stable", "Well-behaved", "Gallant",
    "Logical", "Dauntless", "Winning", "Well-read", "Tidy", "Magnanimous", "High-minded", "Upright", "Noble", "Sweet",
    "Vivacious", "Well-bred", "Chivalrous", "Unfazed", "Punctual", "Effervescent", "Prompt", "Competitive", "Strong", "Objective",
    "Resourceful", "Capable", "Inventive", "Timely", "Personable", "Perfectionist", "Polished", "Precise", "Reflective", "Responsive",
    "Romantic", "Accurate", "Specific", "Tough", "Persuasive", "Popular", "Principled", "Superior", "Inspired", "Profound",
    "Limitless", "Well-rounded", "Tasteful", "Trainable", "Teachable", "Uncomplaining", "Accommodating", "Obliging", "Compliant", "Willing",
    "Disposed", "Prepared", "Equipped", "Primed", "Trusting", "Clear-headed", "Expectant", "Hopeful", "Unwavering", "Neighborly",
    "Studious", "Bookish", "Hypnotic", "Gifted", "No-nonsense", "Mesmerizing", "Far-sighted", "Academic", "Stoic", "Philosophical",
    "Natural", "Diplomatic", "Intellectual", "Pedagogical", "Strategic", "Spontaneous", "Detail-oriented", "Genial", "Gentle", "Discriminating",
    "Selfless", "Amenable", "Amicable", "Parsimonious", "Approachable", "Open", "Avid", "Multifaceted", "Prodigy", "Proficient",
    "Ardent", "Alluring", "Detailed", "Result-oriented", "Admirable", "Amorous", "Fervent", "Forbearing", "Enthralling", "Anticipative",
    "Giving", "Communicative", "Nice", "Receptive", "Futurist", "Cordial", "Unorthodox", "Artsy", "Kindhearted", "Hospitable",
    # Additional traits from other sources to reach hundreds
    "Adventurous", "Athletic", "Creative", "Intellectual", "Laid-back", "Outgoing", "Introverted", "Funny", "Kind", "Ambitious",
    "Spiritual", "Tech-savvy", "Nature lover", "Pet lover", "Foodie", "Gamer", "Bookworm", "Artistic", "Party animal", "Fitness-focused",
    "Early bird", "Night owl", "Drama-free", "Empathetic", "Sarcastic", "Movie buff", "Music lover", "Dancer", "Photographer", "Skater",
    "Stoner-friendly", "Traveler", "Country music fan", "Rapper", "Rock fan", "Clean freak", "Messy", "Debater", "Politically active", "Broke but fun",
    "Rich kid", "Skincare junkie", "Tattooed", "Pierced", "Vegan", "Carnivore", "Gym rat", "Loyal", "Flirty", "DIY fan",
    "Optimistic", "Romantic", "Independent", "Family-oriented", "Adrenaline junkie", "Homebody", "Fashionista", "Environmentalist", "Entrepreneur", "Musician",
    "Writer", "Coder", "Sports fan", "Coffee addict", "Tea lover", "Wine enthusiast", "Beer connoisseur", "Non-smoker", "Health nut", "Junk food lover",
    "Confident", "Shy", "Charismatic", "Humble", "Competitive"
]
# Generate user data
users = []
for _ in range(100000):
    name = fake.first_name()
    age = random.randint(18, 30)
    gender = random.choice(genders)
    location = random.choice(locations)
    selected_traits = random.sample(traits, k=random.randint(4, 8))
    activity = random.choice(activities)
    pref_gender = random.sample(genders, k=random.randint(1, 3))
    pref_age_min = random.randint(18, 24)
    pref_age_max = random.randint(pref_age_min + 1, 30)
    users.append({
        "Name": name,
        "Age": age,
        "Gender": gender,
        "Location": location,
        "Traits": ", ".join(selected_traits),
        "Activity": activity,
        "Pref_Gender": ", ".join(pref_gender),
        "Pref_Age_Min": pref_age_min,
        "Pref_Age_Max": pref_age_max
    })
# Save to CSV
df = pd.DataFrame(users)
df.to_csv("slidesocial_dummy_users.csv", index=False)
print("✅ Done! File saved as 'slidesocial_dummy_users.csv'")